name: ESP-IDF CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: 'v5.1.2' # You can specify a version here, or let it use the latest stable
          target: esp32s3 # Specify your target here
        run: |
          echo "IDF_PATH is: $IDF_PATH"
          ls -la $IDF_PATH/examples/get-started/hello_world
          idf.py build
